# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Oda"
license = "MIT"
licenselink = "https://github.com/attwad/oda/blob/master/LICENSE.md"
description = "A simple theme for hugo based on Google material design"
homepage = "http://butnotfor.me/"
tags = ["material", "google", "simple", "mobile"]
features = ["blog"]
min_version = "0.21"

[author]
  name = "Timothe Faudot"
  homepage = "https://github.com/attwad/"
